services:
  - type: web
    name: fastapi-url-shortener
    runtime: python
    buildCommand: ""
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - fromDotEnv: true
